version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - resume-postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  resume-postgres:
