FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base as build
WORKDIR /app
COPY . .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run --filter=web build
RUN pnpm deploy --filter=web --prod /prod/web

FROM base
WORKDIR /prod/web
COPY --from=build /prod/web .
EXPOSE 4000
CMD [ "pnpm", "start:migrate:prod" ]
